### ISSUE TITLE
`/docs` コマンドが使用できない

### ISSUE THREAD

**Issue by tubuanha** [eve0415/DevTool#11]
`/docs` コマンドが使用できません。
API が503エラーを返すのが原因と思われます。

![39475E78-BEC0-4BA6-A001-F5EF38A3BD44](https://user-images.githubusercontent.com/70151015/153784167-e1a84132-c384-4381-85db-b43ca1a94ef0.jpeg)

**Comment by eve0415** [comment]
お待たせしました。修正しましたことをお知らせいたします。
またなにかありましたら、お気軽に声掛けお願いしますm(__)m
