### ISSUE TITLE
Bug: git url expand feature won't insert language identifer from the second message

### ISSUE THREAD

**Issue by mtripg6666tdr** [eve0415/DevTool#13]
same as title, for example: 
![image](https://user-images.githubusercontent.com/56076195/157616223-2df9ac0c-b616-40fe-9f47-6b19d098ecf0.png)

**Comment by eve0415** [comment]
Re-opening as it wasn't fixed correctly

**Comment by eve0415** [comment]
Will be fixed on next deploy
